/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_cascade_QueryResults */

#ifndef _Included_io_cascade_QueryResults
#define _Included_io_cascade_QueryResults
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_cascade_QueryResults
 * Method:    getReplyMap
 * Signature: (J)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_io_cascade_QueryResults_getReplyMap
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
