#pragma once
#include <cascade/cascade.hpp>

#ifdef ENABLE_EVALUATION
#define TLT_CLIENT_SENT         TLT_DAIRYFARMDEMO(0)
#define TLT_FRONTEND_TRIGGERED  TLT_DAIRYFARMDEMO(1)
#define TLT_FRONTEND_PREDICTED  TLT_DAIRYFARMDEMO(2)
#define TLT_FRONTEND_FORWARDED  TLT_DAIRYFARMDEMO(3)
#define TLT_COMPUTE_TRIGGERED   TLT_DAIRYFARMDEMO(4)
#define TLT_COMPUTE_INFERRED    TLT_DAIRYFARMDEMO(5)
#define TLT_COMPUTE_FORWARDED   TLT_DAIRYFARMDEMO(6)
#define TLT_STORAGE_TRIGGERED   TLT_DAIRYFARMDEMO(7)
#endif
